stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/raw
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/raw
    - src/model_evaluation.py
    outs:
    - reports/metrics.json


metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
